### ISSUE TITLE
New ideas

### ISSUE THREAD

**Issue by Johnnywick1** [rsh1337/weather-app#8]
I don't know if you finished this project, but I have some new ideas (don't know if you can manage it):

1.  There is no Farenheit unit.
2. When I turn on the page for the first time, e.g. in incognito mode, a pop-up window appears in browser that forces me to allow the location. Google doesn't like this. Here's a page about it: https://developer.chrome.com/docs/lighthouse/best-practices/geolocation-on-start?hl=en
And here are probably the solutions:

https://github.com/GoogleChrome/lighthouse/blob/main/core/audits/dobetterweb/geolocation-on-start.js
https://web.dev/articles/user-location?hl=en
If you have time you can read it.
In  these  apps there is no this problem (https://my-weather-app-wm.netlify.app/ or here https://weatherapp-felipefmedeiros.vercel.app/). It searches for a location automatically without asking for the user's permission, and that's exactly what it's all about. In this app Google doesn't see a problem.

3.  There is no Sunset time. 
4. When you search cities there is no choice . I mean many cities have the same names. Could you make an autocomplete, whe anybody searches location? (City, state, country)

Thank you

**Comment by rsh1337** [comment]
Hello, thank you for the suggestions, but unfortunately, I regret to inform you that I have discontinued my involvement with this website. It was initially conceived as a side project, but now, with shifting priorities and less available time, I have decided to redirect my efforts elsewhere. Once again, thank you for your contributions and understanding.

**Comment by Johnnywick1** [comment]
OK, I understand. Best regards.
